package com.ir.util;

import java.io.File;

import org.elasticsearch.common.xcontent.ToXContent;

public class Constants {

	public static final String newline = System.getProperty("line.separator");

	public static final String trec07p = getAbsPath() + "trec07p";
	public static final String dataFol = getAbsPath() + "trec07p/data/";
	public static final String fullFol = getAbsPath() + "trec07p/full/";
	public static final String spamHamInfo = fullFol + "index";

	public static String clusterName = "elasticsearch";

	public static String stoplistPath = getAbsPath() + "stoplist.txt";

	public static String indexName = "spam_trec07p";
	public static String typeName = "document";
	public static String nGramIndexName = "ngram_spam_trec07p";
	public static String nGramTypeName = "document";

	public static String lstDocInfo = "trec07pInfo.txt";
	public static String nGramLstDocInfo = "ngram_trec07pInfo.txt";
	
	
	public static String esFieldBody = "body";

	public static String[] ngrams = { "porn", "free", "win", "sex", "horny", "click here" };
//	public static String[] ngrams = {  "click here" };

	// Boolean that controls if the index created is a ngram or a unigram
	public static boolean ngram = false;


	public static final String data_matrix = getAbsPath() + "data_matrix.arff";
	public static final String data_matrix_with_mailId = getAbsPath() + "data_matrix_with_id.arff";
	public static String data_matrix_test = getAbsPath() + "data_matrix_test.arff";
	public static String data_matrix_train = getAbsPath() + "data_matrix_train.arff";

	public static String trainSparseMatrix = "trainSparseMatrix.txt";
	public static String testSparseMatrix = "testSparseMatrix.txt";
	public static String trainSparseMatrixId = "trainSparseMatrixId.txt";
	public static String testSparseMatrixId = "testSparseMatrixId.txt";

	public static String term_termId = "term_termId_map.txt";

	public static int topNUnigrams = 1000;

	// This file is generated by liblinear after training the sparse matrix
	public static String linearModel = "linear.model";

	
//	public static final String data_matrix = getAbsPath() + "data_matrix.arff";
//	public static final String data_matrix_with_queryNo_docno = getAbsPath() + "data_matrix_with_id.arff";
//	public static String qrels = getAbsPath() + "AP_DATA/qrels.adhoc.51-100.AP89.txt";
//	public static String allQueris = getAbsPath() + "AP_DATA/query_desc.51-100.short.txt";
//
//	public static String okapi = getAbsPath() + "HW1_Result/Okapi_Result.txt";
//	public static String tfidf = getAbsPath() + "HW1_Result/TFIDF_Result.txt";
//	public static String bm25 = getAbsPath() + "HW1_Result/BM25_Result.txt";
//	public static String mercer = getAbsPath() + "HW1_Result/Mercer_Result.txt";
//	public static String laplace = getAbsPath() + "HW1_Result/Laplace_Result.txt";
//
//	public static String trainingQueries = getAbsPath() + "trainingQueries.txt";
//	public static String testingQueries = getAbsPath() + "testingQueries.txt";
	
	public static String getAbsPath(){
		// Shows you the path of your Project Folder
		String absolutePath = new File(".").getAbsolutePath();    	
    	int last = absolutePath.length() - 1;
    	// Remove the dot at the end of path
    	absolutePath = absolutePath.substring(0, last);
		return absolutePath;
	}
}
